In [1]:
import torch

> 矩阵可以和行列向量相乘,和行向量的结果是行向量,和列向量的结果是列向量,结果数值是相同的

In [3]:
x = torch.ones(10, 2)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])

In [5]:
y = torch.ones(2)
y

tensor([1., 1.])

In [6]:
y_ = y.reshape(-1, 1)
y_

tensor([[1.],
        [1.]])

In [7]:
x @ y
# 和行向量结果是行向量

tensor([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

In [8]:
x @ y_
# 和列向量结果是列向量

tensor([[2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.],
        [2.]])

In [9]:
(x @ y_).flatten() == x @ y

tensor([True, True, True, True, True, True, True, True, True, True])